### ISSUE TITLE
Wrap const arguments and return type for python and SIL 

### ISSUE THREAD

**Issue by Laeeth** [kaleidicassociates/autowrap#41] opened 2018-12-18 04:48 UTC
Not sure what to do.  Maybe just copy and dup if argument copyable.  So you register a lambda as a shim that takes whatever pyd gives you and passes it to function in form required.  And it strips off const on return as I think pyd doesn't know what to do with that.

**Comment by atilaneves** [comment] 2018-12-18 14:10
Duplicate of #42

**Closed by atilaneves** 2018-12-18 14:10 UTC
Labels: Python, bug, pyd
